# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: "myapp"
  namespace: default
  labels:
    app: "myapp"
spec:
  containers:
    - name: myapp
      image: "docker.io/library/fastapi-tf:latest"
      imagePullPolicy: Never
  restartPolicy: Always

---

