# This RayService manifest is configured for the fastapi-transformers project.
# Uses Ray 2.50.0 with Python 3.11 (matches the Dockerfile and pyproject.toml)
# The Docker image includes Ray, the application code, and all dependencies.

apiVersion: ray.io/v1
kind: RayService
metadata:
  name: fastapi-transformer-service
spec:
  serviceUnhealthySecondThreshold: 900
  deploymentUnhealthySecondThreshold: 300
  serveConfigV2: |
    applications:
      - name: transformer-app
        import_path: serve_app:deployment_graph
        route_prefix: /
        runtime_env: {}
    # Note: runtime_env is empty since the application code is baked into the Docker image

  rayClusterConfig:
    rayVersion: "2.50.0"
    headGroupSpec:
      rayStartParams: {}
      template:
        spec:
          containers:
            - name: ray-head
              image: crhftd01.azurecr.io/myapp:latest
              ports:
              - containerPort: 6379
                name: gcs-server
              - containerPort: 8265
                name: dashboard
              - containerPort: 10001
                name: client
              resources:
                limits:
                  cpu: "1"
                  memory: "3Gi"
                requests:
                  cpu: "500m"
                  memory: "1536Mi"
    workerGroupSpecs:
      - replicas: 1
        minReplicas: 1
        maxReplicas: 2
        groupName: small-group
        rayStartParams: {}
        template:
          spec:
            containers:
              - name: ray-worker
                image: crhftd01.azurecr.io/myapp:latest
                resources:
                  limits:
                    cpu: "1"
                    memory: "2Gi"
                  requests:
                    cpu: "500m"
                    memory: "1Gi"
