name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  uv-test:
    name: uv-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest

  acr-push:
    name: acr-push
    runs-on: ubuntu-latest
    needs: uv-test

    steps:
      - uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name crhftd01

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -t crhftd01.azurecr.io/myapp:latest \
            -t crhftd01.azurecr.io/myapp:ray-2.50.0-py311 \
            .
