name: Terraform Infrastructure Deployment
on:
  workflow_dispatch:

jobs:
  terraform-ci:
    name: Terraform CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: hashicorp/setup-terraform@v3
        name: Terraform setup

      - id: plan
        name: Terraform Plan
        env:
          ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
        run: |
          cd infra/azure/terraform
          terraform init
          terraform validate
          terraform plan -no-color

      - run: echo ${{ steps.plan.outputs.stdout }}
        name: Print Outputs

      - run: echo ${{ steps.plan.outputs.stderr }}
        name: Print Errors

      - run: echo ${{ steps.plan.outputs.exitcode }}
        name: Print exitcode
